import { Component } from "react";
import { Alert, Col, Row } from "react-bootstrap";
import LoadingIndicator from "../common/LoadingIndicator";
import IMovie from "../../models/IMovie";
import { LoadingStatus } from "../../models/types";
import MovieListItem from "./MovieListItem";

type Props = {
    TabName: string
} 

type State = {
    status: LoadingStatus,
    movies?: IMovie[],
    error?: Error,
    data: string
};



const movies_in_theaters = [
    {
        "id": "1",
        "title": "Black Panther",
        "year": "2018",
        "genres": [
          "Action",
          "Adventure",
          "Sci-Fi"
        ],
        "ratings": [
          4,
          1,
          9,
          6,
          2,
          10,
          6,
          5,
          1,
          7,
          4,
          5,
          6,
          5,
          6,
          3,
          10,
          10,
          8,
          2,
          5,
          3,
          4,
          6,
          6,
          7,
          9,
          4,
          4,
          9
        ],
        "poster": "MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_SY500_CR0,0,337,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT134M",
        "releaseDate": "2018-02-14",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "After the events of Captain America: Civil War, King T'Challa returns home to the reclusive, technologically advanced African nation of Wakanda to serve as his country's new leader. However, T'Challa soon finds that he is challenged for the throne from factions within his own country. When two foes conspire to destroy Wakanda, the hero known as Black Panther must team up with C.I.A. agent Everett K. Ross and members of the Dora Milaje, Wakandan special forces, to prevent Wakanda from being dragged into a world war.                Written by\nEditor",
        "actors": [
          "Chadwick Boseman",
          "Michael B. Jordan",
          "Lupita Nyong'o"
        ],
        "imdbRating": 7,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
        "id": "2",
        "title": "Grottmannen Dug",
        "year": "2018",
        "genres": [
          "Animation",
          "Adventure",
          "Comedy"
        ],
        "ratings": [
          7,
          9,
          6,
          1,
          3,
          8,
          3,
          8,
          7,
          6,
          10,
          3,
          6,
          8,
          3,
          5,
          6,
          6,
          8,
          2,
          7,
          9,
          1,
          1,
          10,
          2,
          3,
          6,
          3,
          5
        ],
        "poster": "MV5BYWMxYWVjNzAtMTY0YS00YWQyLWExMGItMjUxODkwYzQyNzMwXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_SY500_CR0,0,328,500_AL_.jpg",
        "contentRating": "PG",
        "duration": "PT89M",
        "releaseDate": "2018-03-23",
        "averageRating": 0,
        "originalTitle": "Early Man",
        "storyline": "Set at the dawn of time, when prehistoric creatures and woolly mammoths roamed the earth, Early Man tells the story of Dug, along with sidekick Hognob as they unite his tribe against a mighty enemy Lord Nooth and his Bronze Age City to save their home.",
        "actors": [
          "Tom Hiddleston",
          "Eddie Redmayne",
          "Maisie Williams"
        ],
        "imdbRating": 6.3,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BYWMxYWVjNzAtMTY0YS00YWQyLWExMGItMjUxODkwYzQyNzMwXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_SY500_CR0,0,328,500_AL_.jpg"
    },
    {
        "id": "3",
        "title": "Aiyaary",
        "year": "2018",
        "genres": [
          "Action",
          "Crime",
          "Drama"
        ],
        "ratings": [
          1,
          2,
          8,
          10,
          3,
          8,
          8,
          6,
          1,
          8,
          4,
          1,
          9,
          5,
          7,
          8,
          9,
          8,
          10,
          10,
          8,
          3,
          1,
          2,
          5,
          7,
          9,
          9,
          10,
          7
        ],
        "poster": "MV5BMjI1NTk0NTc1OV5BMl5BanBnXkFtZTgwNTMwMTE4NDM@._V1_SY500_CR0,0,281,500_AL_.jpg",
        "contentRating": "",
        "duration": "PT157M",
        "releaseDate": "2018-02-16",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Two officers with patriotic hearts suddenly have a fallout. The mentor, Colonel Abhay Singh has complete faith in the country's system while protégé Major Jai Bakshi thinks differently due to a recent stint in surveillance.",
        "actors": [
          "Anupam Kher",
          "Sidharth Malhotra",
          "Naseeruddin Shah"
        ],
        "imdbRating": "",
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjI1NTk0NTc1OV5BMl5BanBnXkFtZTgwNTMwMTE4NDM@._V1_SY500_CR0,0,281,500_AL_.jpg"
    },
    {
        "id": "4",
        "title": "Samson",
        "year": "2018",
        "genres": [
          "Action",
          "Drama"
        ],
        "ratings": [
          9,
          6,
          5,
          7,
          5,
          8,
          9,
          7,
          1,
          1,
          9,
          2,
          9,
          7,
          8,
          7,
          5,
          3,
          3,
          1,
          2,
          10,
          10,
          2,
          1,
          9,
          6,
          8,
          6,
          8
        ],
        "poster": "MV5BYThiMjg4ZDAtNjk5ZS00ZTUxLThmM2ItMGI0ZTE1NjRhNWNmXkEyXkFqcGdeQXVyNTQ3MjE4NTU@._V1_SY500_CR0,0,334,500_AL_.jpg",
        "contentRating": "PG-13",
        "duration": "",
        "releaseDate": "2018-02-16",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "A Hebrew with an unusual gift of strength must respond properly to the call of God on his life in order to lead his people out of enslavement. After his youthful ambition leads to a tragic marriage, his acts of revenge thrust him into direct conflict with the Philistine army. As his brother mounts a tribal rebellion, only Samson's relationship with a Philistine seductress and his final surrender - both to the Philistines and to God - turns imprisonment and blindness into final victory.                Written by\nPure Flix",
        "actors": [
          "Jackson Rathbone",
          "Billy Zane",
          "Taylor James"
        ],
        "imdbRating": 5,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BYThiMjg4ZDAtNjk5ZS00ZTUxLThmM2ItMGI0ZTE1NjRhNWNmXkEyXkFqcGdeQXVyNTQ3MjE4NTU@._V1_SY500_CR0,0,334,500_AL_.jpg"
    },
    {
        "id": "5",
        "title": "Loveless",
        "year": "2017",
        "genres": [
          "Drama"
        ],
        "ratings": [
          7,
          5,
          7,
          6,
          10,
          8,
          8,
          7,
          3,
          7,
          3,
          4,
          5,
          10,
          8,
          10,
          1,
          7,
          2,
          10,
          10,
          3,
          5,
          2,
          9,
          7,
          7,
          3,
          5,
          1
        ],
        "poster": "MV5BMzU3ODQ3MzQ5Nl5BMl5BanBnXkFtZTgwMDQwMDIzNDM@._V1_SY500_CR0,0,338,500_AL_.jpg",
        "contentRating": "R",
        "duration": "PT127M",
        "releaseDate": "2017-06-01",
        "averageRating": 0,
        "originalTitle": "Nelyubov",
        "storyline": "Still living under the same roof, the Moscow couple of Boris and Zhenya is in the terrible final stages of a bitter divorce. Under those circumstances, as both have already found new partners, the insults pour down like rain in this toxic familial battle zone, always pivoting around the irresolvable and urgent matter of Alyosha's custody, their 12-year-old only son. Unheard, unloved, and above all, unwanted, the introverted and unhappy boy feels that he is an intolerable burden, however, what his parents don't know is that he can hear every single word. As a result, when Boris and Zhenya finally realize that Alyosha has been missing for nearly two days, it is already too late. But is this a simple case of a runaway teenager?                Written by\nNick Riganas",
        "actors": [
          "Maryana Spivak",
          "Aleksey Rozin",
          "Matvey Novikov"
        ],
        "imdbRating": 7.8,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMzU3ODQ3MzQ5Nl5BMl5BanBnXkFtZTgwMDQwMDIzNDM@._V1_SY500_CR0,0,338,500_AL_.jpg"
    },
    {
        "id": "6",
        "title": "L'amant double",
        "year": "2017",
        "genres": [
          "Drama",
          "Romance",
          "Thriller"
        ],
        "ratings": [
          5,
          8,
          9,
          8,
          10,
          2,
          7,
          2,
          9,
          8,
          5,
          1,
          9,
          5,
          9,
          5,
          7,
          10,
          5,
          8,
          2,
          3,
          5,
          4,
          6,
          9,
          3,
          7,
          1,
          4
        ],
        "poster": "MV5BMTg5NjUyMzAyOV5BMl5BanBnXkFtZTgwMTU4Njk2NDM@._V1_SY500_CR0,0,337,500_AL_.jpg",
        "contentRating": "",
        "duration": "PT107M",
        "releaseDate": "2017-05-26",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Disenchanted with the ephemeral glamour of the modelling world, Chloé, a vulnerable Parisian woman of 25, is convinced that the severe and persistent abdominal pains she's been suffering, stem mainly from a psychosomatic disorder. As a result, the reserved beauty will soon find herself on the couch of the charming therapist, Dr Paul Meyer, nevertheless, the mutual and unfailing sexual attraction between them will make it impossible to continue with the therapy. Before long, the ecstatic, yet unexplored lovers will move in together, however, Paul's obscure past will inevitably lead Chloé to the conclusion that there's definitely more to him than meets the eye. Is the doe-eyed woman lured into a world of hallucinations and dream-like sequences?                Written by\nNick Riganas",
        "actors": [
          "Marine Vacth",
          "Jérémie Renier",
          "Jacqueline Bisset"
        ]
    }
];

const movies_coming = [
    {
      "id": "1",
      "title": "Game Night",
      "year": "2018",
      "genres": [
        "Action",
        "Comedy",
        "Crime"
      ],
      "ratings": [
        2,
        10,
        1,
        10,
        6,
        2,
        5,
        2,
        9,
        7,
        5,
        3,
        7,
        7,
        1,
        4,
        5,
        9,
        2,
        8,
        10,
        8,
        1,
        10,
        7,
        10,
        8,
        6,
        7,
        6
      ],
      "poster": "MV5BMjQxMDE5NDg0NV5BMl5BanBnXkFtZTgwNTA5MDE2NDM@._V1_SY500_CR0,0,337,500_AL_.jpg",
      "contentRating": "11",
      "duration": "PT100M",
      "releaseDate": "2018-02-28",
      "averageRating": 0,
      "originalTitle": "",
      "storyline": "A group of friends who meet regularly for game nights find themselves trying to solve a murder mystery.",
      "actors": [
        "Rachel McAdams",
        "Jesse Plemons",
        "Jason Bateman"
      ],
      "imdbRating": "",
      "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjQxMDE5NDg0NV5BMl5BanBnXkFtZTgwNTA5MDE2NDM@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
      "id": "2",
      "title": "Area X: Annihilation",
      "year": "2018",
      "genres": [
        "Adventure",
        "Drama",
        "Fantasy"
      ],
      "ratings": [
        2,
        6,
        2,
        3,
        9,
        5,
        3,
        10,
        6,
        7,
        3,
        1,
        6,
        6,
        1,
        7,
        8,
        8,
        7,
        2,
        3,
        2,
        10,
        4,
        9,
        8,
        2,
        2,
        6,
        3
      ],
      "poster": "MV5BMTk2Mjc2NzYxNl5BMl5BanBnXkFtZTgwMTA2OTA1NDM@._V1_SY500_CR0,0,320,500_AL_.jpg",
      "contentRating": "R",
      "duration": "",
      "releaseDate": "2018-02-23",
      "averageRating": 0,
      "originalTitle": "Annihilation",
      "storyline": "A biologist's husband disappears. She puts her name forward for an expedition into an environmental disaster zone, but does not find what she's expecting. The expedition team is made up of the biologist, an anthropologist, a psychologist, a surveyor, and a linguist.",
      "actors": [
        "Tessa Thompson",
        "Jennifer Jason Leigh",
        "Natalie Portman"
      ],
      "imdbRating": "",
      "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTk2Mjc2NzYxNl5BMl5BanBnXkFtZTgwMTA2OTA1NDM@._V1_SY500_CR0,0,320,500_AL_.jpg"
    },
    {
      "id": "3",
      "title": "Hannah",
      "year": "2017",
      "genres": [
        "Drama"
      ],
      "ratings": [
        1,
        10,
        4,
        9,
        10,
        1,
        9,
        3,
        4,
        4,
        3,
        2,
        3,
        3,
        1,
        1,
        6,
        7,
        10,
        7,
        7,
        8,
        1,
        3,
        10,
        3,
        1,
        9,
        7,
        3
      ],
      "poster": "MV5BNWJmMWIxMjQtZTk0Mi00YTE0LTkyNzAtYzQxYjcwYjE4ZDk2XkEyXkFqcGdeQXVyMTc4MzI2NQ@@._V1_SY500_SX350_AL_.jpg",
      "contentRating": "",
      "duration": "PT95M",
      "releaseDate": "2018-01-24",
      "averageRating": 0,
      "originalTitle": "",
      "storyline": "Intimate portrait of a woman drifting between reality and denial when she is left alone to grapple with the consequences of her husband's imprisonment.",
      "actors": [
        "Charlotte Rampling",
        "André Wilms",
        "Stéphanie Van Vyve"
      ],
      "imdbRating": 6.5,
      "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BNWJmMWIxMjQtZTk0Mi00YTE0LTkyNzAtYzQxYjcwYjE4ZDk2XkEyXkFqcGdeQXVyMTc4MzI2NQ@@._V1_SY500_SX350_AL_.jpg"
    },
    {
      "id": "4",
      "title": "The Lodgers",
      "year": "2017",
      "genres": [
        "Drama",
        "Horror",
        "Romance"
      ],
      "ratings": [
        7,
        5,
        1,
        5,
        4,
        10,
        2,
        7,
        6,
        4,
        10,
        5,
        1,
        5,
        3,
        6,
        9,
        1,
        3,
        4,
        9,
        1,
        7,
        6,
        7,
        5,
        7,
        2,
        10,
        10
      ],
      "poster": "MV5BM2FhM2E1MTktMDYwZi00ODA1LWI0YTYtN2NjZjM3ODFjYmU5XkEyXkFqcGdeQXVyMjY1ODQ3NTA@._V1_SY500_CR0,0,337,500_AL_.jpg",
      "contentRating": "R",
      "duration": "PT92M",
      "releaseDate": "2018-03-09",
      "averageRating": 0,
      "originalTitle": "",
      "storyline": "1920, rural Ireland. Anglo Irish twins Rachel and Edward share a strange existence in their crumbling family estate. Each night, the property becomes the domain of a sinister presence (The Lodgers) which enforces three rules upon the twins: they must be in bed by midnight; they may not permit an outsider past the threshold; if one attempts to escape, the life of the other is placed in jeopardy. When troubled war veteran Sean returns to the nearby village, he is immediately drawn to the mysterious Rachel, who in turn begins to break the rules set out by The Lodgers. The consequences pull Rachel into a deadly confrontation with her brother - and with the curse that haunts them.",
      "actors": [
        "Charlotte Vega",
        "David Bradley",
        "Moe Dunford"
      ],
      "imdbRating": 5.8,
      "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BM2FhM2E1MTktMDYwZi00ODA1LWI0YTYtN2NjZjM3ODFjYmU5XkEyXkFqcGdeQXVyMjY1ODQ3NTA@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
      "id": "5",
      "title": "Beast of Burden",
      "year": "2018",
      "genres": [
        "Action",
        "Crime",
        "Drama"
      ],
      "ratings": [
        9,
        5,
        5,
        5,
        5,
        6,
        10,
        6,
        6,
        9,
        6,
        2,
        2,
        9,
        4,
        6,
        6,
        9,
        7,
        8,
        7,
        10,
        8,
        5,
        3,
        1,
        1,
        5,
        6,
        2
      ],
      "poster": "MV5BMjEyNTM3MDQ2NV5BMl5BanBnXkFtZTgwMDI5Nzk1NDM@._V1_SY500_CR0,0,336,500_AL_.jpg",
      "contentRating": "R",
      "duration": "",
      "releaseDate": "2018-02",
      "averageRating": 0,
      "originalTitle": "",
      "storyline": "Sean Haggerty only has an hour to deliver his illegal cargo. An hour to reassure a drug cartel, a hitman, and the DEA that nothing is wrong. An hour to make sure his wife survives. And he must do it all from the cockpit of his Cessna.",
      "actors": [
        "Daniel Radcliffe",
        "Grace Gummer",
        "Pablo Schreiber"
      ],
      "imdbRating": "",
      "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjEyNTM3MDQ2NV5BMl5BanBnXkFtZTgwMDI5Nzk1NDM@._V1_SY500_CR0,0,336,500_AL_.jpg"
    },
    {
      "id": "6",
      "title": "The Chamber",
      "year": "2016",
      "genres": [
        "Horror",
        "Thriller"
      ],
      "ratings": [
        2,
        10,
        7,
        10,
        9,
        9,
        7,
        4,
        6,
        2,
        1,
        10,
        9,
        4,
        6,
        8,
        3,
        5,
        1,
        1,
        1,
        5,
        6,
        9,
        5,
        4,
        8,
        8,
        8,
        8
      ],
      "poster": "MV5BNTVlODgwMjgtZGUzMy00ZTY1LWIyMDEtYTI2Y2JlYzVjZTNkXkEyXkFqcGdeQXVyNTg0MDM1MzY@._V1_SY500_CR0,0,337,500_AL_.jpg",
      "contentRating": "",
      "duration": "PT88M",
      "releaseDate": "2017-03-10",
      "averageRating": 0,
      "originalTitle": "",
      "storyline": "A claustrophobic survival thriller set beneath the Yellow Sea off the coast of North Korea where the pilot of a small submersible craft and a three man Special Ops team on a secret recovery mission become trapped underwater in a fight for survival.",
      "actors": [
        "Johannes Kuhnke",
        "Charlotte Salt",
        "James McArdle"
      ],
      "imdbRating": 4.4,
      "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BNTVlODgwMjgtZGUzMy00ZTY1LWIyMDEtYTI2Y2JlYzVjZTNkXkEyXkFqcGdeQXVyNTg0MDM1MzY@._V1_SY500_CR0,0,337,500_AL_.jpg"
    }
  ];

const top_rated_india = [
    {
      "title": "Anand",
      "year": "1971",
      "genres": [
        "Drama"
      ],
      "ratings": [
        5,
        6,
        8,
        1,
        2,
        5,
        8,
        2,
        8,
        6,
        10,
        6,
        3,
        7,
        6,
        4,
        1,
        10,
        3,
        6,
        5,
        3,
        9,
        8,
        7,
        2,
        4,
        10,
        5,
        9
      ],
      "poster": "MV5BMjE0Mzk3OTk2NF5BMl5BanBnXkFtZTgwMTQ1NDk5NTE@._V1_SY250_CR0,0,187,250_AL_.jpg",
      "contentRating": "",
      "duration": "PT122M",
      "releaseDate": "1971-03-12",
      "averageRating": 0,
      "originalTitle": "",
      "storyline": "A melodramatic tale of a man with a terminal disease. The story begins with Dr Bhaksar winning a literary prize for his book about a patient called Anand. The rest is flashback. Anand, the title character, is suffering from lymphosarcoma of the intestine. He, however appears to be cheerful on the outside and is determined to extract as much pleasure from his remaining lifespan as is possible. Dr. Bhaskar his physician tends to Anand in his last days. After Anand dies we can however still hear his voice which was recorded on a tape. Dr Bhakser writes a book on his patient and wins a literary prize for it                Written by\nAnonymous",
      "actors": [
        "Rajesh Khanna",
        "Amitabh Bachchan",
        "Sumita Sanyal"
      ],
      "imdbRating": 8.9,
      "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjE0Mzk3OTk2NF5BMl5BanBnXkFtZTgwMTQ1NDk5NTE@._V1_SY250_CR0,0,187,250_AL_.jpg"
    },
    {
      "title": "Dangal",
      "year": "2016",
      "genres": [
        "Action",
        "Biography",
        "Drama"
      ],
      "ratings": [
        5,
        6,
        3,
        9,
        6,
        9,
        7,
        6,
        4,
        2,
        7,
        1,
        10,
        7,
        7,
        6,
        2,
        4,
        2,
        5,
        7,
        8,
        6,
        7,
        3,
        3,
        4,
        6,
        8,
        1
      ],
      "poster": "MV5BMTQ4MzQzMzM2Nl5BMl5BanBnXkFtZTgwMTQ1NzU3MDI@._V1_SY500_CR0,0,356,500_AL_.jpg",
      "contentRating": "",
      "duration": "PT161M",
      "releaseDate": "2016-12-23",
      "averageRating": 0,
      "originalTitle": "",
      "storyline": "Biopic of Mahavir Singh Phogat, who taught wrestling to his daughters Babita Kumari and Geeta Phogat. Geeta Phogat was India's first female wrestler to win at the 2010 Commonwealth Games, where she won the gold medal (55 kg) while her sister Babita Kumari won the silver (52 kg).                Written by\nDibyayan_Chakravorty",
      "actors": [
        "Aamir Khan",
        "Sakshi Tanwar",
        "Fatima Sana Shaikh"
      ],
      "imdbRating": 8.9,
      "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ4MzQzMzM2Nl5BMl5BanBnXkFtZTgwMTQ1NzU3MDI@._V1_SY500_CR0,0,356,500_AL_.jpg"
    },
    {
      "title": "Drishyam",
      "year": "2013",
      "genres": [
        "Crime",
        "Drama",
        "Thriller"
      ],
      "ratings": [
        4,
        7,
        4,
        6,
        1,
        8,
        6,
        4,
        4,
        6,
        4,
        1,
        5,
        9,
        4,
        7,
        5,
        6,
        5,
        1,
        8,
        3,
        9,
        1,
        7,
        4,
        6,
        10,
        6,
        6
      ],
      "poster": "MV5BYmY3MzYwMGUtOWMxYS00OGVhLWFjNmUtYzlkNGVmY2ZkMjA3XkEyXkFqcGdeQXVyMTExNDQ2MTI@._V1_SX330_CR0,0,330,432_AL_.jpg",
      "contentRating": "",
      "duration": "PT160M",
      "releaseDate": "2013-12-19",
      "averageRating": 0,
      "originalTitle": "",
      "storyline": "Georgekutty (Mohanlal) is a cable TV network owner in a remote and hilly village in Kerala. He lives a happy life with his wife and 2 girls. The first half revolves around the depiction of their happy family. Anju (Ansiba), Georgekutty's daughter goes to a school trip in between the proceedings. After a few days a guy who had been at the school trip with her meets Anju. He blackmails her with a video of her that he had captured during the school trip. In the course of events he is accidentally killed by Rani (Meena) and Anju. Georgekutty on returning home is appraised of the events and thus begins a cat and mouse game as the murdered person is the son of IG Geeta Prabhakar (Asha Sharath) and Prabhakar (Siddique). How the family weathers the storm that ensues during the murder investigation forms the rest of the story leading to a deeply satisfying and unexpected climax.                Written by\nAthul",
      "actors": [
        "Mohanlal",
        "Meena",
        "Ansiba"
      ],
      "imdbRating": 8.9,
      "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BYmY3MzYwMGUtOWMxYS00OGVhLWFjNmUtYzlkNGVmY2ZkMjA3XkEyXkFqcGdeQXVyMTExNDQ2MTI@._V1_SX330_CR0,0,330,432_AL_.jpg"
    },
    {
      "title": "Nayakan",
      "year": "1987",
      "genres": [
        "Crime",
        "Drama"
      ],
      "ratings": [
        6,
        3,
        2,
        1,
        8,
        10,
        5,
        8,
        1,
        10,
        6,
        9,
        6,
        5,
        1,
        6,
        9,
        1,
        1,
        3,
        3,
        9,
        4,
        9,
        8,
        1,
        3,
        8,
        4,
        10
      ],
      "poster": "MV5BNTI2Zjc5ODMtNGE0NC00YjU5LTk0NjktZjU4ZDRlZDFkZWU0XkEyXkFqcGdeQXVyNjc5Mjg4Nzc@._V1_SY480_SX320_AL_.jpg",
      "contentRating": "",
      "duration": "PT145M",
      "releaseDate": "1987-07-31",
      "averageRating": 0,
      "originalTitle": "",
      "storyline": "A small boy (Ratnavelu) from Tamilnadu sees his father, a labor leader, killed in cold blood by a policeman. He kills the policeman and runs away to the city of Bombay. From there, the story traces his ascent to become a mafia chief (Velu Naicker).                Written by\nSathyanarayanan Narayanaswamy <sathya@ntd.comsat.com>",
      "actors": [
        "Kamal Haasan",
        "Saranya Ponvannan",
        "Delhi Ganesh"
      ],
      "imdbRating": 8.9,
      "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BNTI2Zjc5ODMtNGE0NC00YjU5LTk0NjktZjU4ZDRlZDFkZWU0XkEyXkFqcGdeQXVyNjc5Mjg4Nzc@._V1_SY480_SX320_AL_.jpg"
    },
    {
      "title": "Anbe Sivam",
      "year": "2003",
      "genres": [
        "Adventure",
        "Comedy",
        "Drama"
      ],
      "ratings": [
        9,
        7,
        1,
        6,
        10,
        5,
        9,
        5,
        3,
        7,
        2,
        10,
        2,
        3,
        1,
        2,
        3,
        1,
        3,
        3,
        8,
        7,
        9,
        3,
        4,
        9,
        3,
        1,
        10,
        1
      ],
      "poster": "MV5BNWQxY2MyNmUtOTkxZC00MmQ3LWFkMjMtNWU3YmFlZDM5YTBhXkEyXkFqcGdeQXVyNjQ2MjQ5NzM@._V1_SX352_CR0,0,352,499_AL_.jpg",
      "contentRating": "",
      "duration": "PT160M",
      "releaseDate": "2003-01-14",
      "averageRating": 0,
      "originalTitle": "",
      "storyline": "Nallasivam (Kamal Haasan) and Anbarasu (Madhavan) are drawn together by the strings of fate after they come into contact at the Bhuvaneshwar airport. Anbarasu is an advertisement director, while Nallasivam is a trade unionist. Fate entwines their travel plans, and they end up travelling to Chennai together. In the course of their journey, Anbarasu, born with a golden spoon, is touched by the realities of the sufferings of a normal human being when he witnesses the dead and the injured during a train accident, and he volunteers to donate his blood, which is of a very rare group, despite his fear of blood. The flashback of Nallasivam is recounted during one of their journeys. Nallasivam is a communist trade unionist, who fights for higher wages for his comrades. By chance, he falls in love with the daughter Bala (Kiran) of a rich industrialist, Bala's father, Padaiyacchi (Nasser). Due to the opposition, they plan to elope and get married, but unfortunately, Nallasivam meets with an ...                Written by\nNiranjan Venkatraman <v.niranjan@ieee.org>",
      "actors": [
        "Kamal Haasan",
        "Madhavan",
        "Kiran Rathod"
      ],
      "imdbRating": 8.9,
      "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BNWQxY2MyNmUtOTkxZC00MmQ3LWFkMjMtNWU3YmFlZDM5YTBhXkEyXkFqcGdeQXVyNjQ2MjQ5NzM@._V1_SX352_CR0,0,352,499_AL_.jpg"
    },
    {
      "title": "Gol Maal",
      "year": "1979",
      "genres": [
        "Comedy",
        "Romance"
      ],
      "ratings": [
        7,
        9,
        10,
        8,
        8,
        9,
        8,
        9,
        9,
        2,
        9,
        4,
        3,
        9,
        3,
        3,
        10,
        8,
        8,
        10,
        3,
        10,
        9,
        3,
        3,
        6,
        2,
        2,
        6,
        4
      ],
      "poster": "MV5BMjA4OTczODgxNF5BMl5BanBnXkFtZTgwMDAzMTU2NDE@._V1_SY250_CR0,0,187,250_AL_.jpg",
      "contentRating": "",
      "duration": "PT144M",
      "releaseDate": "1979-04-20",
      "averageRating": 0,
      "originalTitle": "",
      "storyline": "Ramprasad is a recent college graduate who finds a job with a finicky man, Bhavani Shankar, who believes that a man without a mustache is a man without a character. Bhavani Shankar is also against any of his employees indulging in recreation of any kind. When Ramprasad is caught by his boss at a soccer match, he has to invent a twin brother, the clean-shaven Laxman Prasad, to save his job. When Bhavani's daughter falls in love with the clean-shaven Laxman Prasad, and insists on marrying him, and Bhavani insists she should marry Ramprasad, things take a whacky turn. A fake mother and a hilarious chase are other enjoyable features involved in this comedy.                Written by\nVijay",
      "actors": [
        "Amol Palekar",
        "Bindiya Goswami",
        "Deven Verma"
      ],
      "imdbRating": 8.7,
      "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA4OTczODgxNF5BMl5BanBnXkFtZTgwMDAzMTU2NDE@._V1_SY250_CR0,0,187,250_AL_.jpg"
    }
  ];

const top_rated_movies = [
    {
      "title": "Baazigar",
      "year": "1993",
      "genres": [
        "Crime",
        "Drama",
        "Musical"
      ],
      "ratings": [
        4,
        3,
        5,
        8,
        5,
        5,
        3,
        10,
        9,
        8,
        5,
        9,
        10,
        5,
        8,
        9,
        1,
        1,
        5,
        7,
        7,
        10,
        7,
        8,
        1,
        6,
        6,
        5,
        10,
        9
      ],
      "poster": "MV5BMTc3OTE1MDAxNV5BMl5BanBnXkFtZTgwNjM1NDk5NTE@._V1_SY250_CR0,0,187,250_AL_.jpg",
      "contentRating": "",
      "duration": "PT175M",
      "releaseDate": "1993-11-12",
      "averageRating": 0,
      "originalTitle": "",
      "storyline": "Widowed Madan Chopra lives a very wealthy lifestyle with two daughters, Seema and Priya. His passion is car racing, and realizing that he is not young anymore, has his last race and wins - only to find out that another competitor, Vicky Malhotra, let him win. Madan befriends Vicky, introduces him to Priya and invites him to work for him in Bombay. Vicky and Priya are attracted to each other, much to Madan's delight and he announces their marriage. Before that could happen, Seema kills herself by throwing herself down from the roof of a multi-storied building. While Madan wants to close this case due to embarrassment, Seema meets with her college friend, Police Inspector Karan, and together they begin to unravel a plot that may well end Madan and the lives of others as well.                Written by\nrAjOo (gunwanti@hotmail.com)",
      "actors": [
        "Shah Rukh Khan",
        "Rakhee Gulzar",
        "Kajol"
      ],
      "imdbRating": 7.8,
      "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc3OTE1MDAxNV5BMl5BanBnXkFtZTgwNjM1NDk5NTE@._V1_SY250_CR0,0,187,250_AL_.jpg"
    },
    {
      "title": "24",
      "year": "2016",
      "genres": [
        "Action",
        "Romance",
        "Sci-Fi"
      ],
      "ratings": [
        5,
        1,
        5,
        1,
        3,
        9,
        3,
        2,
        8,
        6,
        7,
        2,
        9,
        9,
        9,
        10,
        6,
        5,
        1,
        10,
        7,
        4,
        5,
        8,
        6,
        2,
        4,
        10,
        9,
        6
      ],
      "poster": "MV5BZmYyNWRmNjUtODg5OC00YmRjLTkwYWMtMjY5NjA5ZjhkNDg3XkEyXkFqcGdeQXVyNDA1NTY2Nzk@._V1_SY500_CR0,0,333,500_AL_.jpg",
      "contentRating": "",
      "duration": "PT164M",
      "releaseDate": "2016-05-06",
      "averageRating": 0,
      "originalTitle": "",
      "storyline": "A Sci-Fi family revenge drama happening between a scientist, his evil brother and the scientist's son, over a time travel gadget.                Written by\nNaveen Sankaran",
      "actors": [
        "Suriya",
        "Samantha Ruth Prabhu",
        "Nithya Menon"
      ],
      "imdbRating": 8,
      "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BZmYyNWRmNjUtODg5OC00YmRjLTkwYWMtMjY5NjA5ZjhkNDg3XkEyXkFqcGdeQXVyNDA1NTY2Nzk@._V1_SY500_CR0,0,333,500_AL_.jpg"
    },
    {
      "title": "Jodhaa Akbar",
      "year": "2008",
      "genres": [
        "Action",
        "Adventure",
        "Biography"
      ],
      "ratings": [
        7,
        2,
        3,
        8,
        6,
        1,
        4,
        2,
        1,
        10,
        6,
        3,
        7,
        4,
        4,
        1,
        3,
        9,
        5,
        10,
        2,
        6,
        9,
        1,
        3,
        7,
        9,
        7,
        3,
        9
      ],
      "poster": "MV5BMTI1ODQ2MDIxMl5BMl5BanBnXkFtZTcwNTc3Mzk1MQ@@._V1_SY361_SX250_AL_.jpg",
      "contentRating": "",
      "duration": "PT213M",
      "releaseDate": "2008-02-15",
      "averageRating": 0,
      "originalTitle": "",
      "storyline": "Jodhaa Akbar is a sixteenth century love story about a marriage of alliance that gave birth to true love between a great Mughal Emperor, Akbar and a Rajput princess, Jodhaa. Politically, success knew no bounds for Emperor Akbar, After having secured the Hindu Kush, he furthered his realm by conquest until his empire extended from Afghanistan to the Bay of Bengal, and from the Himalayas to the Godhavari River. Through a shrewd blend of tolerance, generosity and force, Akbar won the allegiance of the Rajputs, the most belligerent Hindus. But little did Akbar know that when he married Jodhaa, a fiery Rajput princess, in order to further strengthen his relations with the Rajputs, he would in turn be embarking upon a new journey - the journey of true love. The daughter of King Bharmal of Amer, Jodhaa resented being reduced to a mere political pawn in this marriage of alliance, and Akbar's biggest challenge now did not merely lie in winning battles, but in winning the love of Jodhaa - a ...                Written by\nhEmRaJ (gavin_coolhgr@hotmail.com)",
      "actors": [
        "Hrithik Roshan",
        "Aishwarya Rai Bachchan",
        "Sonu Sood"
      ],
      "imdbRating": 7.6,
      "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTI1ODQ2MDIxMl5BMl5BanBnXkFtZTcwNTc3Mzk1MQ@@._V1_SY361_SX250_AL_.jpg"
    },
    {
      "title": "Wake Up Sid",
      "year": "2009",
      "genres": [
        "Comedy",
        "Drama",
        "Romance"
      ],
      "ratings": [
        3,
        6,
        7,
        10,
        6,
        7,
        3,
        3,
        1,
        4,
        10,
        2,
        6,
        3,
        6,
        1,
        6,
        7,
        8,
        4,
        10,
        9,
        10,
        4,
        6,
        2,
        5,
        6,
        2,
        4
      ],
      "poster": "MV5BMTg2NTk2MjU5NV5BMl5BanBnXkFtZTcwNTY0Nzg4Mg@@._V1_SY489_SX324_AL_.jpg",
      "contentRating": "",
      "duration": "PT138M",
      "releaseDate": "2009-10-02",
      "averageRating": 0,
      "originalTitle": "",
      "storyline": "In Mumbai, Sid Mehra is, in the words of his father, an arrogant, spoiled brat. He lives with a doting mother, subservient brother, and a father who covers his expenses and credit card bills. Sid takes his college finals then starts work at his father's business; he lasts less than a week before walking out. At a graduation party, he meets Aisha, newly arrived from Calcutta and set on becoming a writer. He shows her the city and helps her refurbish a rented flat. He asks if she'd like to progress from friend to something more, but she says no: he lacks ambition and isn't her type. Will her words, his exam results, a confrontation with his parents, and a break with his friends be enough to wake Sid up?                Written by\n<jhailey@hotmail.com>",
      "actors": [
        "Ranbir Kapoor",
        "Konkona Sen Sharma",
        "Supriya Pathak"
      ],
      "imdbRating": 7.6,
      "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg2NTk2MjU5NV5BMl5BanBnXkFtZTcwNTY0Nzg4Mg@@._V1_SY489_SX324_AL_.jpg"
    },
    {
      "title": "Saala Khadoos",
      "year": "2016",
      "genres": [
        "Action",
        "Drama",
        "Sport"
      ],
      "ratings": [
        2,
        3,
        7,
        2,
        7,
        2,
        2,
        10,
        1,
        2,
        7,
        6,
        4,
        2,
        2,
        1,
        6,
        3,
        4,
        2,
        2,
        2,
        3,
        5,
        7,
        10,
        7,
        8,
        3,
        10
      ],
      "poster": "MV5BM2Q5YmM3YjMtOTE2Mi00MDg5LThkZjctYzUxOWU2ZTM1ZDk4XkEyXkFqcGdeQXVyMTExNDQ2MTI@._V1_SY334_SX250_AL_.jpg",
      "contentRating": "",
      "duration": "PT109M",
      "releaseDate": "2016-01-29",
      "averageRating": 0,
      "originalTitle": "",
      "storyline": "An under-fire boxing coach, Prabhu is transferred from Hisar in Haryana to Chennai as his bosses at the Boxing Council do not like his disrespectful rule-breaking unconventional ways. In Chennai, he chances upon the raw fighting talent of Madhi, the sibling of aspiring boxer Lakshmi. He decides to put all his effort to tame Madhie and get her to shine but he is repeatedly put off by her playfulness & distrust.                Written by\nPipingHotViews",
      "actors": [
        "Madhavan",
        "Nassar",
        "Radha Ravi"
      ],
      "imdbRating": 7.7,
      "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BM2Q5YmM3YjMtOTE2Mi00MDg5LThkZjctYzUxOWU2ZTM1ZDk4XkEyXkFqcGdeQXVyMTExNDQ2MTI@._V1_SY334_SX250_AL_.jpg"
    },
    {
      "title": "Qayamat Se Qayamat Tak",
      "year": "1988",
      "genres": [
        "Action",
        "Drama",
        "Musical"
      ],
      "ratings": [
        5,
        2,
        10,
        3,
        2,
        5,
        8,
        1,
        4,
        5,
        3,
        6,
        9,
        8,
        9,
        9,
        8,
        4,
        10,
        2,
        1,
        1,
        5,
        9,
        3,
        1,
        9,
        8,
        8,
        7
      ],
      "poster": "MV5BMTY4MDQyMDUzOF5BMl5BanBnXkFtZTcwMjUyNTAzMQ@@._V1_SY250_SX168_AL_.jpg",
      "contentRating": "",
      "duration": "PT162M",
      "releaseDate": "1988-03-01",
      "averageRating": 0,
      "originalTitle": "",
      "storyline": "Both Dhanraj Singh and Randhir Singh are two bitter and old time enemies. They faced a disastrous situation when there children, Raj and Rashmi falls deeply in love. They openly declares there hatred for one another and will do anything in there power even kill but they will not accept there children's choice. But Raj and Rashmi is dedicated to there love and is not willing to accept the fact that there dads are enemies.                Written by\ngAvInDrA (brave_loverboy2004@hotmail.com)",
      "actors": [
        "Aamir Khan",
        "Juhi Chawla",
        "Goga Kapoor"
      ],
      "imdbRating": 7.6,
      "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTY4MDQyMDUzOF5BMl5BanBnXkFtZTcwMjUyNTAzMQ@@._V1_SY250_SX168_AL_.jpg"
    }
  ]

const favourit = [
    {
        "id": "1",
        "title": "Black Panther",
        "year": "2018",
        "genres": [
          "Action",
          "Adventure",
          "Sci-Fi"
        ],
        "ratings": [
          4,
          1,
          9,
          6,
          2,
          10,
          6,
          5,
          1,
          7,
          4,
          5,
          6,
          5,
          6,
          3,
          10,
          10,
          8,
          2,
          5,
          3,
          4,
          6,
          6,
          7,
          9,
          4,
          4,
          9
        ],
        "poster": "MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_SY500_CR0,0,337,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT134M",
        "releaseDate": "2018-02-14",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "After the events of Captain America: Civil War, King T'Challa returns home to the reclusive, technologically advanced African nation of Wakanda to serve as his country's new leader. However, T'Challa soon finds that he is challenged for the throne from factions within his own country. When two foes conspire to destroy Wakanda, the hero known as Black Panther must team up with C.I.A. agent Everett K. Ross and members of the Dora Milaje, Wakandan special forces, to prevent Wakanda from being dragged into a world war.                Written by\nEditor",
        "actors": [
          "Chadwick Boseman",
          "Michael B. Jordan",
          "Lupita Nyong'o"
        ],
        "imdbRating": 7,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
        "id": "2",
        "title": "Grottmannen Dug",
        "year": "2018",
        "genres": [
          "Animation",
          "Adventure",
          "Comedy"
        ],
        "ratings": [
          7,
          9,
          6,
          1,
          3,
          8,
          3,
          8,
          7,
          6,
          10,
          3,
          6,
          8,
          3,
          5,
          6,
          6,
          8,
          2,
          7,
          9,
          1,
          1,
          10,
          2,
          3,
          6,
          3,
          5
        ],
        "poster": "MV5BYWMxYWVjNzAtMTY0YS00YWQyLWExMGItMjUxODkwYzQyNzMwXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_SY500_CR0,0,328,500_AL_.jpg",
        "contentRating": "PG",
        "duration": "PT89M",
        "releaseDate": "2018-03-23",
        "averageRating": 0,
        "originalTitle": "Early Man",
        "storyline": "Set at the dawn of time, when prehistoric creatures and woolly mammoths roamed the earth, Early Man tells the story of Dug, along with sidekick Hognob as they unite his tribe against a mighty enemy Lord Nooth and his Bronze Age City to save their home.",
        "actors": [
          "Tom Hiddleston",
          "Eddie Redmayne",
          "Maisie Williams"
        ],
        "imdbRating": 6.3,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BYWMxYWVjNzAtMTY0YS00YWQyLWExMGItMjUxODkwYzQyNzMwXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_SY500_CR0,0,328,500_AL_.jpg"
    },
    {
        "id": "3",
        "title": "Aiyaary",
        "year": "2018",
        "genres": [
          "Action",
          "Crime",
          "Drama"
        ],
        "ratings": [
          1,
          2,
          8,
          10,
          3,
          8,
          8,
          6,
          1,
          8,
          4,
          1,
          9,
          5,
          7,
          8,
          9,
          8,
          10,
          10,
          8,
          3,
          1,
          2,
          5,
          7,
          9,
          9,
          10,
          7
        ],
        "poster": "MV5BMjI1NTk0NTc1OV5BMl5BanBnXkFtZTgwNTMwMTE4NDM@._V1_SY500_CR0,0,281,500_AL_.jpg",
        "contentRating": "",
        "duration": "PT157M",
        "releaseDate": "2018-02-16",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Two officers with patriotic hearts suddenly have a fallout. The mentor, Colonel Abhay Singh has complete faith in the country's system while protégé Major Jai Bakshi thinks differently due to a recent stint in surveillance.",
        "actors": [
          "Anupam Kher",
          "Sidharth Malhotra",
          "Naseeruddin Shah"
        ],
        "imdbRating": "",
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjI1NTk0NTc1OV5BMl5BanBnXkFtZTgwNTMwMTE4NDM@._V1_SY500_CR0,0,281,500_AL_.jpg"
    },
    {
        "id": "4",
        "title": "Samson",
        "year": "2018",
        "genres": [
          "Action",
          "Drama"
        ],
        "ratings": [
          9,
          6,
          5,
          7,
          5,
          8,
          9,
          7,
          1,
          1,
          9,
          2,
          9,
          7,
          8,
          7,
          5,
          3,
          3,
          1,
          2,
          10,
          10,
          2,
          1,
          9,
          6,
          8,
          6,
          8
        ],
        "poster": "MV5BYThiMjg4ZDAtNjk5ZS00ZTUxLThmM2ItMGI0ZTE1NjRhNWNmXkEyXkFqcGdeQXVyNTQ3MjE4NTU@._V1_SY500_CR0,0,334,500_AL_.jpg",
        "contentRating": "PG-13",
        "duration": "",
        "releaseDate": "2018-02-16",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "A Hebrew with an unusual gift of strength must respond properly to the call of God on his life in order to lead his people out of enslavement. After his youthful ambition leads to a tragic marriage, his acts of revenge thrust him into direct conflict with the Philistine army. As his brother mounts a tribal rebellion, only Samson's relationship with a Philistine seductress and his final surrender - both to the Philistines and to God - turns imprisonment and blindness into final victory.                Written by\nPure Flix",
        "actors": [
          "Jackson Rathbone",
          "Billy Zane",
          "Taylor James"
        ],
        "imdbRating": 5,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BYThiMjg4ZDAtNjk5ZS00ZTUxLThmM2ItMGI0ZTE1NjRhNWNmXkEyXkFqcGdeQXVyNTQ3MjE4NTU@._V1_SY500_CR0,0,334,500_AL_.jpg"
    },
    {
        "id": "5",
        "title": "Loveless",
        "year": "2017",
        "genres": [
          "Drama"
        ],
        "ratings": [
          7,
          5,
          7,
          6,
          10,
          8,
          8,
          7,
          3,
          7,
          3,
          4,
          5,
          10,
          8,
          10,
          1,
          7,
          2,
          10,
          10,
          3,
          5,
          2,
          9,
          7,
          7,
          3,
          5,
          1
        ],
        "poster": "MV5BMzU3ODQ3MzQ5Nl5BMl5BanBnXkFtZTgwMDQwMDIzNDM@._V1_SY500_CR0,0,338,500_AL_.jpg",
        "contentRating": "R",
        "duration": "PT127M",
        "releaseDate": "2017-06-01",
        "averageRating": 0,
        "originalTitle": "Nelyubov",
        "storyline": "Still living under the same roof, the Moscow couple of Boris and Zhenya is in the terrible final stages of a bitter divorce. Under those circumstances, as both have already found new partners, the insults pour down like rain in this toxic familial battle zone, always pivoting around the irresolvable and urgent matter of Alyosha's custody, their 12-year-old only son. Unheard, unloved, and above all, unwanted, the introverted and unhappy boy feels that he is an intolerable burden, however, what his parents don't know is that he can hear every single word. As a result, when Boris and Zhenya finally realize that Alyosha has been missing for nearly two days, it is already too late. But is this a simple case of a runaway teenager?                Written by\nNick Riganas",
        "actors": [
          "Maryana Spivak",
          "Aleksey Rozin",
          "Matvey Novikov"
        ],
        "imdbRating": 7.8,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMzU3ODQ3MzQ5Nl5BMl5BanBnXkFtZTgwMDQwMDIzNDM@._V1_SY500_CR0,0,338,500_AL_.jpg"
    },
    {
        "id": "6",
        "title": "L'amant double",
        "year": "2017",
        "genres": [
          "Drama",
          "Romance",
          "Thriller"
        ],
        "ratings": [
          5,
          8,
          9,
          8,
          10,
          2,
          7,
          2,
          9,
          8,
          5,
          1,
          9,
          5,
          9,
          5,
          7,
          10,
          5,
          8,
          2,
          3,
          5,
          4,
          6,
          9,
          3,
          7,
          1,
          4
        ],
        "poster": "MV5BMTg5NjUyMzAyOV5BMl5BanBnXkFtZTgwMTU4Njk2NDM@._V1_SY500_CR0,0,337,500_AL_.jpg",
        "contentRating": "",
        "duration": "PT107M",
        "releaseDate": "2017-05-26",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Disenchanted with the ephemeral glamour of the modelling world, Chloé, a vulnerable Parisian woman of 25, is convinced that the severe and persistent abdominal pains she's been suffering, stem mainly from a psychosomatic disorder. As a result, the reserved beauty will soon find herself on the couch of the charming therapist, Dr Paul Meyer, nevertheless, the mutual and unfailing sexual attraction between them will make it impossible to continue with the therapy. Before long, the ecstatic, yet unexplored lovers will move in together, however, Paul's obscure past will inevitably lead Chloé to the conclusion that there's definitely more to him than meets the eye. Is the doe-eyed woman lured into a world of hallucinations and dream-like sequences?                Written by\nNick Riganas",
        "actors": [
          "Marine Vacth",
          "Jérémie Renier",
          "Jacqueline Bisset"
        ]
    }
];

class MoviesList extends Component<Props, State> {

    state: State = {
        status: 'LOADING',
        data: this.props.TabName
    };

    render() {

        let el;

        const {status, movies, error} = this.state;

        switch ( status ) {
            case 'LOADING':
                el = (
                    <LoadingIndicator 
                        size="large"
                        message="We are fetching the movies. Please wait..." />
                );
                break;
            case 'LOADED':
                el = (
                    <Row xs={2} md={3} lg={6}>
                        {
                            movies?.map(
                                (movie, idx) => (
                                    <Col key={idx} className="d-flex align-items-stretch my-3">
                                        <MovieListItem movie={movie} />
                                    </Col>
                                )
                            )
                        }
                    </Row>
                );
                break;
            case 'ERROR_LOADING':
                el = (
                    <Alert variant="danger">
                        {error?.message}
                    </Alert>
                );
                break;
        }

        return el;
        // return (
        //     <div>
        //         <div>{this.props.TabName}</div>
        //     </div>
        // );
    }

    componentDidMount() {
        setTimeout(() => {
            this.setState({
                status: 'LOADED',
                movies: movies_in_theaters
               
            }
            // this.setState({
            //     status: 'ERROR_LOADING',
            //     error: new Error ('some err')
               
            // }
            );
        }, 1000);
    }
}

export default MoviesList;